In [1]:
from sklearn import preprocessing 

In [2]:
labels = ['cat', 'dog', 'horse', 'cat', 'dog']

In [3]:
label_encoder = preprocessing.LabelEncoder()
label_encoder.fit_transform(labels) #giving labels to the 'labels'

array([0, 1, 2, 0, 1], dtype=int64)

In [4]:
for i, item in enumerate(label_encoder.classes_): #enumerate returns object and value
    print item, '->',i

cat -> 0
dog -> 1
horse -> 2


In [5]:
labels2 = ['cat', 'dog', 'horse', 'cat', 'dog', 'horse', 'cat', 'dog']

In [15]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

labels2 = ['cat', 'dog', 'horse', 'cat', 'dog', 'horse', 'cat', 'dog']
label_encoder = LabelEncoder()
label_encoder2 = label_encoder.fit_transform(labels2)
oneHot_Encoder = OneHotEncoder()
label_encoder2 = label_encoder2.reshape(len(label_encoder2),1)
oneHot_Encoder = oneHot_Encoder.fit_transform(label_encoder2)
print oneHot_Encoder

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 0)	1.0
  (4, 1)	1.0
  (5, 2)	1.0
  (6, 0)	1.0
  (7, 1)	1.0


In [16]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
# for explanation of sparse = False where the location of 1 is specified only
labels2 = ['cat', 'dog', 'horse', 'cat', 'dog', 'horse', 'cat', 'dog']
label_encoder = LabelEncoder()
label_encoder2 = label_encoder.fit_transform(labels2)
oneHot_Encoder = OneHotEncoder(sparse = False)
label_encoder2 = label_encoder2.reshape(len(label_encoder2),1) #reshaping from row vector to column vector
oneHot_Encoder = oneHot_Encoder.fit_transform(label_encoder2)
print oneHot_Encoder

#one column is always dummy i.e for n number of columns, n-1 is compulsory to use the rest is ambigious and can be removed

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
