In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
def deriv(x):
    return x*(1-x) # if we put the value of sigmoid in x, we get derivative

In [4]:
x = np.array([[0,0,1],
             [0,1,1],
             [1,0,1],
             [1,1,1]]) #3 features and hence three in input layer : x1, x2, x3

In [5]:
y = np.array([[0],
             [1],
             [1],
             [0]])

In [6]:
alphas  = [0.001,0.01,0.1,1,10,100,1000] #learning rate range defined

for alpha in alphas:
    print("\nTraining with Alpha = "+str(alpha))
    np.random.seed(1)

In [20]:
for alpha in alphas:
    print("\nTraining with Alpha = "+str(alpha))
    np.random.seed(1) #declaring seed as 1 gives us a random value value that remains fixed over every iteration
    print(np.random.random((1,1))) #1,1 because it generate an ouput along a matrix of dimension 1x1
    synapse_0 = np.random.random((3,4))-1 #row shwows the no. of features and column for the nodes in hidden layer
    synapse_1 = np.random.random((4,1))-1 #row shows nodes in hidden layer ad column in ouput layer 
    # -1 is the bias
    
    for j in range(60001):
        layer_0 = x #input layer
        layer_1 = sigmoid(np.dot(layer_0,synapse_0)) #hidden layer
        layer_2 = sigmoid(np.dot(layer_1,synapse_1)) #ouput layer
    
        layer_2_error = layer_2 - y
    
        if j%1000==0:
            print("Error after" +str(j)+ " iterations = " + str(np.mean(np.abs(layer_2_error))))
        layer_2_delta = layer_2_error*deriv(layer_2)
        layer_1_error = layer_2_delta.dot(synapse_1.T)
        layer_1_delta = layer_1_error*deriv(layer_1)
        synapse_1 -= alpha*(layer_1.T.dot(layer_2_delta))
        synapse_0 -= alpha*(layer_0.T.dot(layer_1_delta))


Training with Alpha = 0.001
[[0.417022]]
Error after0 iterations = 0.4940589603435852
Error after1000 iterations = 0.4939913793541759
Error after2000 iterations = 0.493944832462373
Error after3000 iterations = 0.49391340268171113
Error after4000 iterations = 0.4938924106509104
Error after5000 iterations = 0.49387817004152945
Error after6000 iterations = 0.4938677865301426
Error after7000 iterations = 0.4938589951142864
Error after8000 iterations = 0.49385002970691294
Error after9000 iterations = 0.49383951919970276
Error after10000 iterations = 0.49382640488646307
Error after11000 iterations = 0.493809874955842
Error after12000 iterations = 0.4937893125454236
Error after13000 iterations = 0.4937642545360548
Error after14000 iterations = 0.4937343588403476
Error after15000 iterations = 0.4936993784078896
Error after16000 iterations = 0.4936591405451703
Error after17000 iterations = 0.4936135304459941
Error after18000 iterations = 0.4935624780628329
Error after19000 iterations = 0.49350

Error after47000 iterations = 0.01736994063494295
Error after48000 iterations = 0.017118637750269308
Error after49000 iterations = 0.016877013562007263
Error after50000 iterations = 0.01664447623724545
Error after51000 iterations = 0.016420482804906628
Error after52000 iterations = 0.016204534126606197
Error after53000 iterations = 0.015996170482839557
Error after54000 iterations = 0.015794967687787705
Error after55000 iterations = 0.01560053365979067
Error after56000 iterations = 0.015412505385879367
Error after57000 iterations = 0.015230546228146697
Error after58000 iterations = 0.01505434352753671
Error after59000 iterations = 0.014883606467147783
Error after60000 iterations = 0.014718064162592599

Training with Alpha = 1
[[0.417022]]
Error after0 iterations = 0.4940589603435852
Error after1000 iterations = 0.07924064312467428
Error after2000 iterations = 0.03399526634251888
Error after3000 iterations = 0.024155163651611584
Error after4000 iterations = 0.01948603269688827
Error afte

Error after25000 iterations = 0.3751642038137062
Error after26000 iterations = 0.3751609022289567
Error after27000 iterations = 0.3751577880355944
Error after28000 iterations = 0.3751548442395853
Error after29000 iterations = 0.37515205592427514
Error after30000 iterations = 0.3751494099353095
Error after31000 iterations = 0.3751468946220114
Error after32000 iterations = 0.37514449962364615
Error after33000 iterations = 0.3751422156916532
Error after34000 iterations = 0.3751400345409053
Error after35000 iterations = 0.3751379487245618
Error after36000 iterations = 0.37513595152821644
Error after37000 iterations = 0.37513403687992275
Error after38000 iterations = 0.37513219927335917
Error after39000 iterations = 0.37513043370192517
Error after40000 iterations = 0.3751287356019784
Error after41000 iterations = 0.3751271008037518
Error after42000 iterations = 0.37512552548875333
Error after43000 iterations = 0.37512400615266
Error after44000 iterations = 0.37512253957288905
Error after450

In [11]:
print(synapse_0)

[[-0.27967551 -0.99988563 -0.69766743 -0.85324411]
 [-0.90766141 -0.81373979 -0.65443927 -0.60323253]
 [-0.46118327 -0.58080549 -0.3147805  -0.79554775]]


In [12]:
print(synapse_1)

[[-0.12188256]
 [-0.97261241]
 [-0.32953249]
 [-0.5826952 ]]
